
#Configure ForgeEssentials Core.
[Core]
	#Date-only format
	format_date = "yyyy-MM-dd"
	#Date and time format
	format_date_time = "dd.MM HH:mm"
	#Date and time format with seconds
	format_date_time_seconds = "dd.MM HH:mm:ss"
	#Time-only format
	format_time = "HH:mm"
	#Time-only format with seconds
	format_time_seconds = "HH:mm:ss"
	#Extra Time format to Load GSON data from a different locale and convert it!
	format_gson_compat = "MMM d, yyyy h:mm:ss aa"
	#Specify the file where the modlist will be written to. This path is relative to the ForgeEssentials folder.
	modlistLocation = "modlist.txt"
	#Enable Command Ailases for FE commands
	enableAilases = true
	#Should we overwrite conflicting commands?
	overwriteConflicts = true
	#Check for newer versions of ForgeEssentials on load?
	versionCheck = true
	#Activates developer debug mode. Spams your FML logs.
	debug = false
	#Activates safe mode with will ignore some errors which would normally crash the game.Please only enable this after being instructed to do so by FE team in response to an issue on GitHub!
	safeMode = false
	#Hide WorldEdit commands from /help and only show them in //help command
	hide_worldedit_help = true
	#Log commands to console
	logCommands = false

[Misc]
	#Once this percent of player sleeps, allow the night to pass. Set to 100 to disable.
	#Range: 0 ~ 100
	MajoritySleepThreshold = 100
	#Check if a player's name contains spaces (can gum up some things in FE)
	CheckSpacesInNames = true

#This controls the colors of the various chats output by ForgeEssentials.
#Valid output colors are as follows:
#aqua, black, blue, dark_aqua, dark_blue, dark_gray, dark_green, dark_purple, dark_red
#gold, gray, green, light_purple, red, white, yellow
[Output]
	#Defaults to green.
	confirmationColor = "green"
	#Defaults to red.
	errorOutputColor = "red"
	#Defaults to aqua.
	notificationOutputColor = "aqua"
	#Defaults to yellow.
	warningOutputColor = "yellow"

