
[General]
	#Name of the block to use as material for new portals.
	#Does not override vanilla nether/end portals.
	#Setting this to 'minecraft:portal' is currently not supported.
	portalBlock = "minecraft:glass_pane"

